version: 2

jobs:
  lint:
    working_directory: ~/react-context-subscriber
    docker:
      - image: circleci/node:8@sha256:8023964f3dc5af0e438b766c22215dbb84a65cd7a403847dc3dc879d27069de9
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint
          command: yarn run lint

  flow:
    working_directory: ~/react-context-subscriber
    docker:
      - image: circleci/node:8@sha256:8023964f3dc5af0e438b766c22215dbb84a65cd7a403847dc3dc879d27069de9
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Flow
          command: yarn run flow

  build:
    working_directory: ~/react-context-subscriber
    docker:
      - image: circleci/node:8@sha256:8023964f3dc5af0e438b766c22215dbb84a65cd7a403847dc3dc879d27069de9
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - build
